language: node_js
node_js:
  #- "iojs"
  - "7"
nvm: 
  - 10.11.0
  
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha YOUR_TESTS/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js

